### PR TITLE
test: fix TasksTest

### PR DESCRIPTION
**Pull request by kenjis**
The test method output command output "Commands can output text.".

### CODE REVIEW

**Comment by kenjis** [comment]
@MGatner 

> Run composer-unused -vvv --output-format=github --ansi --no-interaction --no-progress
> Error: codeigniter4/settings is unused
https://github.com/codeigniter4/tasks/runs/5828158630?check_suite_focus=true

It seems tasks use only `setting()` helper.
Can composer-unused detect like that usage?

**Comment by kenjis** [comment]
@paulbalandan @samsonasik 
I don't know why the error shows only on PHP 7.4, not on PHP 8.x.
Do you know why?

```
------ ---------------------------------------------------------------------- 
  Line   src/CronExpression.php                                                
 ------ ---------------------------------------------------------------------- 
  131    Binary operation "%" between string and (string|false) results in an  
         error.                                                                
 ------ ---------------------------------------------------------------------- 
```
https://github.com/codeigniter4/tasks/runs/5828158626?check_suite_focus=true

https://github.com/codeigniter4/tasks/blob/6e6c2d54ebca67fe48e48e58e48e4ae250d6bbc9/src/CronExpression.php#L131

**Comment by samsonasik** [comment]
@kenjis what's the example data is? it seems on format return string, it got : 

```
Notice: A non well formed numeric value encountered 
```

for example:

```php
$time = '/5';
$dateTime = new DateTime('now');
$currentTime = $dateTime->format('Y/m/d');
$period = substr($time, strpos($time, '/') + 1);
var_dump($currentTime % $period);
```

ref https://3v4l.org/MrrB1#v7.4.28

**Review by MGatner — APPROVED** [review]

**Comment by MGatner** [comment]
@kenjis you can provide a Config file that adds a file to a package. It should be almost exactly this, adapter for Settings: https://github.com/tattersoftware/codeigniter4-files/blob/develop/composer-unused.php

**Comment by paulbalandan** [comment]
@kenjis 
If an invalid character range is requested, `substr()` returns an empty string as of PHP 8.0.0; previously, `false` was returned instead.

You can add `?: ''` after the `substr`.
https://phpstan.org/r/826554e0-62f8-4dc9-8605-d76d57a9b1bb

**Comment by kenjis** [comment]
@MGatner Thanks! 
I created a new PR for GitHub Actions and moved commits from this PR.
See #48

**Comment by kenjis** [comment]
@samsonasik @paulbalandan 
Thanks!
I didn't know the change of substr().
https://www.php.net/manual/en/function.substr.php#refsect1-function.substr-changelog

It seems the code needs validation for the values, but for now I added the workaround that
Paul suggested.
See https://github.com/codeigniter4/tasks/pull/48

**Pull request merged**
