### PR TITLE
fix: update needed php version

### PR DESCRIPTION
**Pull request by datamweb**

### CODE REVIEW

**Comment by samsonasik** [comment]
Thank you @datamweb

**Comment by kenjis** [comment]
Why do we need `spark`?

**Comment by samsonasik** [comment]
@kenjis it seems outdated module, I think we need to archive this repo if not maintained...

**Comment by MGatner** [comment]
We want to keep this repo! It's not in bad shape, as far as I know?

`spark` I believe was a mistake (https://github.com/codeigniter4/tasks/pull/17#issuecomment-789389962) and should be removed.

**Comment by kenjis** [comment]
@MGatner If this works, why don't you remove the NOTE?

> NOTE: Just starting development. Not for active consumption or it WILL make your app sick.
https://github.com/codeigniter4/tasks#codeigniter-4-tasks

**Comment by MGatner** [comment]
@lonnieezell Are you ready for Tasks to make an official release?

**Comment by lonnieezell** [comment]
I believe all it needed was better docs, and to get the docs auto-building like Shield has. The only major missing piece is notifications, I think, and that's not required for a 1.0 release.

**Pull request merged**
