### PR TITLE
Add Mock Classes

### PR DESCRIPTION
**Pull request by MGatner**
* Defines the first few Mock classes to assist with testing
* Adds some tests for the Mock classes
* Adds a basic Scheduler service so it will be able to be mocked

### CODE REVIEW

**Comment by lonnieezell** [comment]
I question the need for these mock classes as they are, honestly. Mocks and partial mocks can easily be created by the dev during a test using tools built into PHPUnit or Mockery. Now, if these provided more assertion methods to test the tasks that got ran, etc, they might prove more useful, I think. I can see this being helpful: 

```
$this->scheduler = new MockScheduler();
services()->injectMock('scheduler', $this->scheduler);

// run tests....

$this->scheduler->assertRanTask('foo', function($task) {
   return $task->ranAt('daily');
});
```

I can see that being much more helpful. I haven't been paying close enough attention on the CI front lately but I have a feeling we need to look into more of that there, also.

**Comment by MGatner** [comment]
I think assertions are great. I do also think it will be important for devs to be able to "test" action without actually triggering them, e.g. delete local files without really deleting them.

**Comment by lonnieezell** [comment]
I think you want to test different things at different times, though, right? You want to test that your task does exactly what it's supposed to in isolation, like a Unit test, where you would test whether it deleted the files, etc (which is probably best done using something like vfstream). For those you wouldn't use a mock class but the actual thing. Then you'd want to test that it was called correctly in larger contexts right? It's at this point that a Mock class comes in handy. This can be done really easily with mocks using Mockery, or partial mocks right from PHPUnit itself (IIRC. Maybe that was Mockery I used for that, also). Either way, I'm not convinced these basic mock classes always add capabilities. I know I started the trend in CI4, but I'm pretty sure that was with session and logs to be able to check what content was actually given to them. 

I'm also still on pain meds so am probably missing something lol.

**Comment by MGatner** [comment]
You're not wrong, but I think there's a level of simplicity that goes from "file and forget". I like to do my potential-instrusive tests in one test case with VFStream (or whatever) and then mock the intrusive class globally for all other tests and not have to worry about messy cleanup or disruptive features that have already be tested. Totally fine if this is not the approach you would like for this repo, these are always classes I can use in projects that incorporate Tasks, but I am still keen on the functionality.

**Pull request merged**
