### PR TITLE
chore: update gitattributes

### PR DESCRIPTION
**Pull request by datamweb**

### CODE REVIEW

**Review by kenjis — APPROVED** [review]

**Comment by MGatner** [comment]
I'd actually rather get rid of the **admin/** directory altogether. We don't enforce pre-commit hooks on other libraries and it is one more thing to trip people up.

**Comment by MGatner** [comment]
Open to opinions on that, but I didn't want to miss the opportunity for a discussion even though this PR is absolutely correct.

**Comment by lonnieezell** [comment]
I'm happy to nuke the precommit hook altogether. The only thing really useful to me that doesn't get in the way is code formatting.

**Comment by kenjis** [comment]
The pre-commit just does PHP syntax check and coding style check.
https://github.com/codeigniter4/tasks/blob/develop/admin/pre-commit
I think it is very useful.

Shield also has it.
https://github.com/codeigniter4/shield/blob/develop/admin/pre-commit
But this version seems to be newer and better.

Settings also has.
https://github.com/codeigniter4/settings/blob/develop/admin/pre-commit

**Comment by MGatner** [comment]
Okay, I guess we keep it. Those things drive me crazy, but I always disable them locally anyways so it's not a big deal.

**Review by MGatner — APPROVED** [review]

**Comment by kenjis** [comment]
> Those things drive me crazy

Really? 
I would think that your code would most likely pass the PHP syntax and coding style checks.

**Comment by MGatner** [comment]
@kenjis you give me way too much credit 🤗 My code is full of issues and these tools all help me keep it together. What drives me crazy about the hooks though is how disruptive they are to my workflow: they are either trying to run checks I've already handled, or that I don't want to run right now, and they slow down what should be a very quick operation.

**Pull request merged**
