### PR TITLE
Add MkDocs-Material

### PR DESCRIPTION
**Pull request by michalsn**
**Description**

* Page organization for MkDocs
   * vision.md was left intact to have a reference when it comes to plans and features not yet implemented (this file is not linked anywhere)
* Adds docs workflow
* Adds publish config command

Light mode:
obraz

Dark mode:
obraz

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by lonnieezell — APPROVED** [review]
This looks great, thanks!

**Comment by kenjis** [comment]
Do we need the TOC?
Screenshot 2023-12-15 11 07 54

**Review by kenjis — APPROVED** [review]
Looks great!

**Comment by michalsn** [comment]
> Do we need the TOC?

I removed it from the `Installation` page.

**Comment by MGatner** [comment]
This is awesome! Thanks @michalsn

**Pull request merged**
